### ISSUE TITLE
remove duplicates?

### ISSUE THREAD

**Issue by sckott** [jeroenooms/hunspell#2]
would it make sense to remove duplicates before processing?  perhaps not

e.g., 

```r
words <- c("beer", "wiskey", "wine")
hunspell_check(c(words, words))
[1]  TRUE FALSE  TRUE  TRUE FALSE  TRUE
```

**Comment by jeroenooms** [comment]
I think it's better to let the user wrap the response in `unique` if it wants to filter out duplicates. There are actually valid cases in which you do want to know each occurrence.
