### ISSUE TITLE
Use system dictionaries

### ISSUE THREAD

**Issue by artemklevtsov** [jeroenooms/hunspell#3]
Hi.

I have installed `hunspell` package with many dictionaries. I can create a symlink or copy dicts but it would be better control search path with option. For example:

```r
options(hunspell.path = "/usr/share/hunspell/")
```

```r
get_affix <- function(lang) {
  default <- system.file("dict", lang, paste0( lang, ".aff"), package = "hunspell")
  path <- getOption("hunspell.path", default)
  normalizePath(path, mustWork = TRUE)
}

get_dict <- function(lang) {
  default <- system.file("dict", lang, paste0( lang, ".dic"), package = "hunspell")
  path <- getOption("hunspell.path", default)
  normalizePath(path, mustWork = TRUE)
}
```

**Comment by jeroenooms** [comment]
Actually I think `libhunspell` should pick up on certain environment variables to set the path, but I need to look into this a bit more.

**Comment by jeroenooms** [comment]
It looks like the `hunspell` command line utility searches the following paths:

```c
#define LIBDIR                \
  "/usr/share/hunspell:"      \
  "/usr/share/myspell:"       \
  "/usr/share/myspell/dicts:" \
  "/Library/Spelling"
```

And also checks for the `DICPATH` environment variable. So we should probably do something similar.

**Comment by jeroenooms** [comment]
First attempt: https://github.com/jeroenooms/hunspell/commit/dabcd65fc371406da4ae19953211d60c261fa27e

**Comment by artemklevtsov** [comment]
Also note: RStudio Desktop package contains the `hunspell` English dicts:

```bash
$ ls -1 /usr/lib/rstudio/resources/dictionaries/ | head -n 3
en_AG.aff@
en_AG.dic@
en_AU.aff@

```

**Comment by jeroenooms** [comment]
Ah cool, that's nice.

**Comment by jeroenooms** [comment]
Can you test if this works? I am mostly concerned with the character encoding stuff on non-latin alphabets....

**Comment by artemklevtsov** [comment]
Now it works:

```r
hunspell::hunspell_analyze("Текст", dict = "ru_RU")
#> [[1]]
#> [1] " st:текст"
#> 
```

Do `hunspell_*` not works with vectors?

**Comment by jeroenooms** [comment]
Yes it should work with vectors. What error do you get?

**Comment by artemklevtsov** [comment]
@jeroenooms sorry, my bad :) I tried "It workds fine" instead c("It", "works", "fine").

**Comment by artemklevtsov** [comment]
Additional dictionaries may be installed with RStduio Desktop (Global Options > Spelling). For details: https://support.rstudio.com/hc/en-us/articles/200551916?version=0.99.892&mode=desktop

**Comment by jeroenooms** [comment]
Hmm it doesn't work in windows. I was afraid of that.

**Comment by artemklevtsov** [comment]
What do you think about the `get_dict(lang)` function which download a required language dictionary?

**Comment by jeroenooms** [comment]
I need to figure out the character encoding stuff first. This doesn't work on windows right now when the character encoding of the dictionary doesn't match that of the string in R.

**Comment by artemklevtsov** [comment]
> I need to figure out the character encoding stuff first. This doesn't work on windows right now when the character encoding of the dictionary doesn't match that of the string in R.

First I would try `stringi::stringi::stri_enc_toutf8`.

**Comment by jeroenooms** [comment]
I don't want to depend on stringi. Maybe start with iconv.

**Comment by jeroenooms** [comment]
What encoding is your dictionary in? Can you try: `hunspell_info("ru_RU")` ?

**Comment by artemklevtsov** [comment]
On Linux:

```r
hunspell::hunspell_info(dict = "ru_RU")
#> $dict
#> [1] "/usr/share/hunspell/ru_RU.dic"
#> 
#> $encoding
#> [1] "KOI8-R"
#> 
#> $wordchars
#> [1] "-.'`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\xa3\xb3\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff"
#> 
```

```bash
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE=C
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

**Comment by jeroenooms** [comment]
@artemklevtsov would you mind testing the latest version some more? In particular `hunspell_info()` and `hunspell_find()` with some Russian sentences?

**Comment by artemklevtsov** [comment]
```r
> hunspell_info()
$dict
[1] "/usr/share/hunspell/en_US.dic"

$encoding
[1] "UTF-8"

$wordchars
[1] "0123456789"

> hunspell_info("ru_RU")

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("hunspell_R_hunspell_info", PACKAGE = "hunspell", affix,     dict)
 2: R_hunspell_info(get_affix(dict), get_dict(dict))
 3: hunspell_info("ru_RU")
```

**Comment by jeroenooms** [comment]
Hmm that's very strange. I'm getting this on all my systems:

```
> hunspell_info()
$dict
[1] "/usr/lib/rstudio-server/resources/dictionaries/en_US.dic"

$encoding
[1] "ISO8859-1"

$wordchars
[1] "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþ"
```

and 

```
> hunspell_info("ru_RU")
$dict
[1] "/home/jeroen/R/x86_64-pc-linux-gnu-library/3.2/hunspell/dict/ru_RU.dic"

$encoding
[1] "KOI8-R"

$wordchars
[1] "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzёЁюабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ"
```

**Comment by artemklevtsov** [comment]
All my dicts in the `/usr/share/hunspell/` in UTF-8. Russian dictionary source: http://extensions.libreoffice.org/extension-center/russian-spellcheck-dictionary.-based-on-works-of-aot-group/pscreleasefolder.2011-09-06.6209385965/0.4.0/dict_ru_ru-aot-0-4-0.oxt

**Comment by jeroenooms** [comment]
Sorry for being an idiot but how do I get the `aff` and `dic` file from that `oxt`?

**Comment by jeroenooms** [comment]
ah never mind just renamed it to `.tar.gz` and it worked.

**Comment by artemklevtsov** [comment]
`unzip` also works.

**Comment by jeroenooms** [comment]
These are called `russian-aot` though but it works for me:

```

> hunspell_info("russian-aot")
$dict
[1] "/Users/jeroen/Downloads/ru_utf8/russian-aot.dic"

$encoding
[1] "KOI8-R"

$wordchars
[1] "-.'`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzёЁюабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ"
```

**Comment by jeroenooms** [comment]
Can you maybe try again if it still happens?

**Comment by artemklevtsov** [comment]
Sorry for that. AOT used on my Desktop. Right link: https://bitbucket.org/Shaman_Alex/russian-dictionary-hunspell/downloads/ru_RU_UTF-8_20131101.zip

**Comment by jeroenooms** [comment]
OK thanks I understand the problem now.

**Comment by jeroenooms** [comment]
Could you give it another try?

**Comment by artemklevtsov** [comment]
Seems it works now but characters field is missing:

```r
hunspell::hunspell_info("ru_RU")
#> $dict
#> [1] "/usr/share/hunspell/ru_RU.dic"
#> 
#> $encoding
#> [1] "KOI8-R"
#> 
#> $wordchars
#> [1] "-.'`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzёЁюабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ"
Sys.setenv("DICPATH" = "/tmp/")
hunspell::hunspell_info("ru_RU")
#> $dict
#> [1] "/tmp/ru_RU.dic"
#> 
#> $encoding
#> [1] "UTF-8"
#> 
#> $wordchars
#> [1] "NA"
```

**Comment by jeroenooms** [comment]
Yes apparently utf8 dictionaries do not have a wordchar field, or at least not yours. Could you test some sentences with `hunspell_find` to see if it picks up incorrect words with either dictionary?

**Comment by artemklevtsov** [comment]
Works fine:

```r
hunspell_find("чёртова карова", dict = "ru_RU")
#> [[1]]
#> [1] "карова"
#> 
```

**Comment by jeroenooms** [comment]
This is on CRAN now. Thanks for your suggestions. Feel free to open new issues if you run into other problems.

**Comment by artemklevtsov** [comment]
Thank you for this nice package.
